<?php

error_reporting(E_ALL);

define('ACCOUNT_ID', 'ADD_GUID');
define('SITE_ID', 'ADD_SITE_GUID');
define('TOKEN', 'ADD_TOKEN');

define('SERVER_URL', 'https://staging-api.paypaplane.com/v1.0/payment-requests');

$url = (isset($_SERVER['HTTPS']) ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";

$baseRequest = [
	'accountId' => ACCOUNT_ID,
	'siteId' => SITE_ID,
	'reference' => '',
	'amount' => [
		'amount' => 0,
		'currency' => 'AUD'
	],
	'isZeroValue' => false,
	'isTest' => true,
	'recurrence' => [
		'stages' => [
			[
				'frequency' => 1,
				'period' => 'Month',
				'duration' => 9,
				'description' => 'Monthly Payment',
				'amount' => 100.19,
				'withdrawDay' => 'sale'
			],
			[
				'frequency' => 1,
				'period' => 'Month',
				'duration' => 1,
				'description' => 'Monthly Payment',
				'amount' => 100.28,
				'withdrawDay' => 'sale'
			]
		],
		'backdate' => false,
		'minimumDaysUntilFirstPayment' => 0
	],
	'transactionTypes' =>  ['visa', 'mastercard', 'btau_credit'],
	'metadata' => [
		'type' => 'description',
		'data' => [
			'description' => 'This is the purchase'
		]
	],
	'customer' => [
		'firstName' => 'Test',
		'lastName' => 'Person',
		'email' => 'test+337@paypaplane.com',
		'mobile' => '+61412123123'
	],
	'notify' => [
		'sms' => false,
		'email' => false,
	],
	'integration' => [
		'inline' => [
			'successUrl' => $url . '?action=success',
			'failureUrl' => $url . '?action=failure',
			'abortUrl' => $url . '?action=abort',
		]
	]
];


function createPaymentRequest($data)
{
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, SERVER_URL);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
	curl_setopt($ch, CURLOPT_POST, 1);

	$headers = array();
	$headers[] = 'Authorization: Bearer ' . TOKEN;
	$headers[] = 'Cache-Control: no-cache';
	$headers[] = 'Content-Type: application/json';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	$result = curl_exec($ch);
	if (curl_errno($ch)) {
		echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);

	return json_decode($result, true);
}

// form submitted, prepare request and do redirect
if (isset($_POST['submit'])) {
    $result = createPaymentRequest($baseRequest);
    if (!isset($result['leadUrl'])) {
        echo '<pre>';
        print_r($result);
        echo '</pre>';
    } else {
        header($result['leadUrl']);
    }
	die;
}

?>
<html>
	<head>
		<meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height" />
		<title>Demo Integration</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<style>
			body {
				font-family: Arial, Sans-Serif;
				font-size: 12px;
			}
			h1 {
				font-size: 24px;
				padding-left: 20px;
				text-transform: uppercase;
				font-weight: normal;

			}
			div.main {
				width: 100%;
				min-height: 400px;
			}

			ul {
				list-style: none;
				display: block;
			}

			ul li {
				display: inline;
				float: left;
				width: 160px;
				height: 44px;
				line-height:1.5em;
				padding: 10px 0;
				box-sizing: border-box;
			}

			.bd_l {
				padding-right: 25px;
				text-align: right;
				clear: both;
				line-height: 22px;
			}

			.bd_button {
				clear: both;
				margin-left: 300px;
			}

			#button {
				width: 120px;
				height: 22px;
				background-color: #78B23F;
				border: none;
				color: #fff;
				text-align: center;
				line-height: 0px;

			}

		</style>
	</head>

	<body>
		<div class="container">

			<div class="main">
				<h1>Demo Integration</h1>

				<?php if (isset($_GET['action'])) : ?>
					<h4 style="margin-top: 40px; text-align: center;">Came back on the <strong><?php echo $_GET['action'] ?></strong> URL.</h4>
				<?php else : ?>
					<form id="form1" name="PaymentForm" method="post" action="" >
						<ul>
							<li class="bd_button">
								<input class="bd_l" type="submit" name="submit" id="button" value="Submit"/>
							</li>
						</ul>
					</form>
				<?php endif; ?>
			</div>
		</div>
	</body>
</html>